require 'rake'
require 'rake/clean'

RDOC_OPTS = ["--line-numbers", "--inline-source", '--main', 'README']

begin
  gem 'rdoc', '= 3.12.2'
  gem 'hanna-nouveau'
  RDOC_OPTS.concat(['-f', 'hanna'])
rescue Gem::LoadError
end

rdoc_task_class = begin
  require "rdoc/task"
  RDoc::Task
rescue LoadError
  begin
    require "rake/rdoctask"
    Rake::RDocTask
  rescue LoadError, StandardError
  end
end

if rdoc_task_class
  rdoc_task_class.new do |rdoc|
    rdoc.rdoc_dir = "rdoc"
    rdoc.options += RDOC_OPTS
    rdoc.main = "apetag.rb"
    rdoc.title = "ruby-apetag: APEv2 Tag Reader/Writer"
    rdoc.rdoc_files.add ["apetag.rb"]
  end
end

desc "Package ruby-apetag"
task :package do
  sh %{gem build apetag.gemspec}
end

desc "Run the specs"
task :test do
  sh %{#{FileUtils::RUBY} -I. test/test_apetag.rb}
end
task :default => :test
