desc "Generate rdoc"
task :rdoc do
  rdoc_dir = "rdoc"
  rdoc_opts = ["--line-numbers", "--inline-source", '--title', 'ruby-apetag: APEv2 Tag Reader/Writer']

  begin
    gem 'hanna'
    rdoc_opts.concat(['-f', 'hanna'])
  rescue Gem::LoadError
  end

  rdoc_opts.concat(['--main', 'apetag.rb', "-o", rdoc_dir, 'MIT-LICENSE', 'apetag.rb'])

  FileUtils.rm_rf(rdoc_dir)

  require "rdoc"
  RDoc::RDoc.new.document(rdoc_opts)
end

desc "Build apetag gem"
task :package do
  sh %{gem build apetag.gemspec}
end

desc "Run the specs"
task :test do
  sh %{#{FileUtils::RUBY} #{'-w' if RUBY_VERSION >= '3'} #{'-W:strict_unused_block' if RUBY_VERSION >= '3.4'} -I. test/test_apetag.rb}
end
task :default => :test


desc "Run specs with coverage"
task :test_cov do
  ENV['COVERAGE'] = '1'
  sh %{#{FileUtils::RUBY} -I. test/test_apetag.rb}
end
